# handle -> (files in display order, status, note)
OK,CHK="OK","CHECK"
M = {
"banksia-serrata":(["Banksia Serrata.jpg","IMG_2072 3.heic"],OK,""),
"you-can-rain-on-me":(["Rain on Me.jpg"],OK,""),
"we-are-the-stars-yellow":(["IMG_3051 2.heic"],OK,"Yellow birds on black; series colour guessed from image"),
"we-are-the-stars-green":(["IMG_3049 2.heic"],OK,"Green birds on black"),
"we-are-the-stars-purple":(["IMG_3048 2.heic"],OK,"Purple/pink birds on black"),
"we-are-the-stars-red":(["We Are The Stars 4.jpg"],OK,"Red birds on black, file named 'We Are The Stars 4'"),
"a-poem-with-ai":(["A poem with AI collab.jpg"],OK,""),
"we-are-the-stars":(["We Are The Stars.jpg","We Are The Stars gallery pic.jpg","IMG_2913 5.heic","IMG_2923.jpg"],OK,""),
"i-promise-its-the-last-one":(["IMG_1569.heic","IMG_1573.HEIC"],OK,"Text on painting reads 'I promise this is the last one'"),
"banksia-x-two":(["Banksia Two.jpg"],OK,""),
"banksia-monstera":(["Banksia Monstera.jpg"],OK,""),
"banksia-3":(["Banksia Blue.jpg"],OK,"Confirmed via old website: 30x30 Banksia series (Green, Blue, x Two, Monstera)"),
"banksia-green":(["Banksia Green.jpg"],OK,""),
"berry-me-red":(["Berry Me Red.heic"],OK,""),
"berry-me-purple":(["Berry Me Purple.heic"],OK,""),
"berry-me-green":(["Berry Me Green.heic"],OK,""),
"shes-so-ambitious":(["She's So Ambiticous.PNG","IMG_3244 2.jpg"],OK,"2nd image = room mock-up"),
"yellow-banksia":(["Banksia Yellow.heic"],OK,""),
"oysters":(["Oysters.jpg"],OK,""),
"landscape-drip":(["Landscape Drip.jpg"],OK,""),
"dinner-at-94":(["Dinner at #94.heic","IMG_1140 2.HEIC"],OK,""),
"morning":(["First Light.heic"],OK,"Old website calls it 'First Light, 30x30, $250' (sheet: Morning 35x35 $200)"),
"last-star":(["First Star.heic"],OK,"File named 'First Star'"),
"banksia-aemula":(["Banksia Aemula.jpg","Banksia Aemula cropped.jpg","IMG_2166 2.JPG"],OK,""),
"everyone-loves-lemons":(["Everyone Loves Lemons.heic"],OK,""),
"everyone-loves-limes":(["Everyone Loves Limes.jpg"],OK,""),
"night-birds":(["Stars.jpg"],OK,"Confirmed via old website: 'Night Birds 2, 30x40, $180'"),
"sophia-billy-and-the-eggs":(["Sophia, Billy and the eggs.jpg"],OK,""),

"pink-bits":(["Pink Bits.jpg"],OK,""),
"orchid":(["Orchid G T.jpg"],OK,"Confirmed by user"),
"orchid-2":(["Orchid G.jpg"],OK,"Confirmed by user"),
"shes-so-pretty":(["She's So Pretty.jpg"],OK,""),
"blue-stamen":(["Blue Stamen.jpg"],OK,""),
"ghost-gum":(["CANVA Ghost Gum.jpg"],OK,"From old website (painting says GHOST GUM)"),
"pink-banksia":(["IMG_3247 2.jpg","IMG_3245 2.jpg"],OK,"Confirmed via old website: 'Pink Banksia for Lou, commissioned'"),
"flock-me":(["Kylie Washington. Magnetic Horizon. Painting.jpg"],OK,"Confirmed via old website caption 'Flock Me 45x38'"),
"purple":(["Black Currant.jpg"],OK,"Purple 33x33 painting in old website SOLD grid; Dropbox name 'Black Currant'"),
"green-spray":(["CANVA green 33x33 sold grid.jpg"],OK,"Green-framed 33x33 painting in old website SOLD grid"),
"sunset-field":(["Sunset Field.jpg"],OK,"'Fields and Fields.jpg' is the same image"),
"mandarin-bowl":(["Mandarin Bowl.jpg"],OK,""),
"colour-studies":(["4 colour studies.jpg"],OK,""),
"waratahs":(["Waratah.jpg"],OK,"File 'Waratah'. NOTE: old website shows this one in a SOLD grid. Alternatives: 'Waratah with Frame.jpg', IMG_2797"),
"dusk-flowers":(["Dusk Flowers.jpg"],OK,""),
"tulip":(["Tulip.jpg"],OK,""),
"jack-and-the-bean-stalk":(["Jack and the Bean Stalk.jpg"],OK,""),
"starstruck":(["Starstruck.jpg"],OK,""),
"oranges":(["Oranges.jpg"],OK,""),
"two-pears-in-a-pod":(["Two Pears in a Pod.jpg","IMG_1098.heic"],OK,""),
"sisters":(["Sisters.jpg"],OK,""),
"banksia":(["Banksia.jpg","IMG_3109 2.jpg"],OK,"Long blue banksia + room mock-up"),
"the-road-out":(["The Road Out.jpg","IMG_4105.heic"],OK,""),
"wattle":(["Wattle.jpg"],OK,""),
"grevillea":(["Greveliia.jpg"],OK,""),
"red-protea":(["Red Protea.jpg"],OK,""),
"shes-got-such-a-sunny-disposition":(["She's Got Such a Sunny Disposition.jpeg","IMG_3297.jpg"],OK,""),
"waratah-in-lounge":(["CANVA Waratah straight-on.jpg","Waratah in lounge.jpeg"],OK,"Main image from old website (Waratah 107x90, black frame)"),
# prints found in this folder
"dusk-protea-fine-art-print":(["Dusk Protea in lounge room.PNG"],OK,"Print (room mock-up)"),
"moonlight-banksia-fine-art-print":(["Moonlight Banksia.JPG"],OK,"Print"),
"pining-fine-art-print":(["Pining.JPG"],OK,"Print"),
"queen-of-the-slipstream-fine-art-print":(["Queen of the Slipstream.JPG"],OK,"Print"),
"wattle-me-fine-art-print":(["Wattle Me.JPG"],OK,"Print"),
"night-spawning-fine-art-print":(["night_spawning 2.PNG"],OK,"Print"),
"not-how-i-was-feeling-fine-art-print":(["not_how_i_was_feeling 2.JPG"],OK,"Print; IMG_2171 is the same image"),
}
UNMATCHED = {"Amplified Heart.jpg":"Not in product list",
 "Protea Ink.jpg":"Not in product list",
 "IMG_1582.heic":"Old website: 'Banksia Pods, 30x40, sold' (not in sheet). 3 banksia pods with text 'Banksia pods represent resilience and renewal... Rising from the ash' (2026). Not identified",
 "IMG_1126.HEIC":"Bowl of lemons on red gingham. Not identified (old site has 'Greek Lover and Her Lemons', a different painting)","IMG_1096.heic":"Oysters with lemons on teal (different from 'Oysters.jpg'). Not identified",
 "IMG_2612.JPG":"Digital collage: flowers in terracotta bowl. Probably a print, not identified","IMG_2797 3.HEIC":"Waratah in vase on green. Not identified",
 "Waratah with Frame.jpg":"'WARATAH' painting. Which product?",
 "IMG_8604.HEIC":"Printed curtains. Licensing page, not a product","Sculpture/ (21 files)":"Sculpture: 'Crosses'. No products for this yet"}
NOIMG=["pink-waratah"]  # user has this image from the Excel sheet
