OK,CHK="OK","CHECK"
# handle(without -fine-art-print) -> (files, status, note). Files get NEW names: <handle>-fine-art-print[-n].jpg
P = {
"dusk-protea":(["Dusk Protea.JPG","IMG_0289 3.JPG"],OK,"Straight-on print; room mock-up already uploaded"),
"ill-leave-the-light-on":(["I'll Leave the Light On.JPG","IMG_0295 3.JPG"],OK,""),
"slipstreaming":(["IMG_0293 3.JPG"],CHK,"Unnamed file: blue birds on wave lines, similar to Queen of the Slipstream"),
"cordelia-shadows":(["IMG_0262.JPG"],OK,"Confirmed via old website 'Cordelia Shadows'"),
"ferning":(["Ferning.JPG"],OK,""),
"etching-1":(["Etched 1.jpg"],OK,""),
"etching-2":(["Etched_2.jpeg"],OK,""),
"blood-on-the-table":(["Blood_On_The_Table.jpg"],OK,""),
"banksia-typography":(["Banksia Typography .jpg"],OK,""),
"vessel":(["Vessel.jpg"],OK,""),
"underwater-roll":(["Underwater Roll.jpg"],OK,""),
"turn-lights-on-pink":(["Turn_Lights_On_Criss_Cross.jpg"],OK,"Old website: 'You Turn My Lights On (Brighter)'"),
"turn-lights-on-red":(["Turn_Lights_On_Criss_Cross red.jpg"],OK,""),
"tripdick-1":(["Tripdick1.jpg"],OK,""),
"tripdick-2":(["Tripdick2.jpg"],OK,""),
"tripdick-3":(["Tripdick3.jpg"],OK,""),
"dinner":(["The_Dinner_Table.jpg"],OK,""),
"the-chosen-one":(["The_Chosen_One.jpg"],OK,""),
"starry-ghosts":(["Starry_Ghost.jpg"],OK,""),
"smoky-amber":(["Smoky.jpg"],OK,""),
"shadow-light-tips":(["Shadow_Light_Tips.jpg"],OK,""),
"red-light-district-gum":(["Red_Light_District_Gum.jpg"],OK,""),
"rays":(["Rays.jpg"],OK,""),
"orchid-cut":(["Orchid_Cut.jpg"],OK,""),
"milk-blossom":(["Milk_Blossom.jpg"],OK,""),
"magnolia":(["Madnolia.jpg"],OK,"File and old website both say 'Madnolia'"),
"light-touch-lily":(["Light_Touch.jpg"],OK,""),
"home-is-where-the-heart-is":(["Home_Is_Where_The_Heart_Is.jpg"],OK,""),
"gummy-bear":(["Gummy Bear.jpg"],OK,""),
"grevillea-spinning":(["Grevillea Starlight.jpg"],CHK,"No file named 'Grevillea Spinning'. Closest: 'Grevillea Starlight'"),
"glory-fingers":(["Glory_Fingers (1).jpg"],OK,""),
"from-the-darkness-comes-light":(["From_The_Darkness_There_Comes_Light.jpg"],OK,""),
"everyone-loves-limes":(["Everyone_Loves_Limes .jpg"],OK,""),
"everyone-loves-lemons":(["Everyone_Loves_Lemons.jpg"],OK,""),
"centre-point":(["CenterPoint.jpg"],OK,""),
"noose-around-her-neck":(["A_Noose_Around_Her_Neck.jpg"],OK,""),
"orchid":(["Orchid G T.jpg"],CHK,"Same image as the 'Orchid' original (Orchid G T). Prints folder also has 'Orchid G'"),
"blushing":(["Blushing.jpg"],OK,""),
"spinning-me-around":(["CANVA Spinning Me Around.jpg"],OK,"From old website (caption 'Spinning Me Around')"),
}
DONE=["wattle-me","queen-of-the-slipstream","pining","moonlight-banksia","night-spawning","not-how-i-was-feeling"]  # dusk-protea also has uploaded mock-up
NOIMG=["tips"]
